"""Initial commit

Revision ID: 041b9a01ff73
Revises: 
Create Date: 2023-06-17 16:00:46.421234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041b9a01ff73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('phases',
    sa.Column('phase_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('main_character', sa.String(), nullable=False),
    sa.Column('firs_alternative_character', sa.String(), nullable=True),
    sa.Column('second_alternative_character', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phases')
    op.drop_table('scenarios')
    op.drop_table('users')
    # ### end Alembic commands ###
