"""Modify password and salt types

Revision ID: 1f5640de49b7
Revises: 041b9a01ff73
Create Date: 2023-06-17 16:08:50.536131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5640de49b7'
down_revision = '041b9a01ff73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
