"""Modify back password and salt types

Revision ID: 263ed029d6fa
Revises: 1f5640de49b7
Create Date: 2023-06-17 16:12:25.658830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263ed029d6fa'
down_revision = '1f5640de49b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
